# The services of the project.
#
# Each service listed will be deployed
# to power your Platform.sh project.

mysqldb:
    type: "mariadb:11.4"
    disk: 2048
cache:
  type: redis-persistent:7.2
  disk: 256
